/* Generated by dbus-binding-tool; do not edit! */

#include <glib.h>
#include <dbus/dbus-glib.h>

G_BEGIN_DECLS

#ifndef _DBUS_GLIB_ASYNC_DATA_FREE
#define _DBUS_GLIB_ASYNC_DATA_FREE
static
#ifdef G_HAVE_INLINE
inline
#endif
void
_dbus_glib_async_data_free (gpointer stuff)
{
	g_slice_free (DBusGAsyncData, stuff);
}
#endif

#ifndef DBUS_GLIB_CLIENT_WRAPPERS_com_openedhand_DBus_Tests_Echo
#define DBUS_GLIB_CLIENT_WRAPPERS_com_openedhand_DBus_Tests_Echo

static
#ifdef G_HAVE_INLINE
inline
#endif
gboolean
com_openedhand_DBus_Tests_Echo_echo (DBusGProxy *proxy, const char * IN_string, char ** OUT_echo_string, GError **error)

{
  return dbus_g_proxy_call (proxy, "Echo", error, G_TYPE_STRING, IN_string, G_TYPE_INVALID, G_TYPE_STRING, OUT_echo_string, G_TYPE_INVALID);
}

typedef void (*com_openedhand_DBus_Tests_Echo_echo_reply) (DBusGProxy *proxy, char * OUT_echo_string, GError *error, gpointer userdata);

static void
com_openedhand_DBus_Tests_Echo_echo_async_callback (DBusGProxy *proxy, DBusGProxyCall *call, void *user_data)
{
  DBusGAsyncData *data = (DBusGAsyncData*) user_data;
  GError *error = NULL;
  char * OUT_echo_string;
  dbus_g_proxy_end_call (proxy, call, &error, G_TYPE_STRING, &OUT_echo_string, G_TYPE_INVALID);
  (*(com_openedhand_DBus_Tests_Echo_echo_reply)data->cb) (proxy, OUT_echo_string, error, data->userdata);
  return;
}

static
#ifdef G_HAVE_INLINE
inline
#endif
DBusGProxyCall*
com_openedhand_DBus_Tests_Echo_echo_async (DBusGProxy *proxy, const char * IN_string, com_openedhand_DBus_Tests_Echo_echo_reply callback, gpointer userdata)

{
  DBusGAsyncData *stuff;
  stuff = g_slice_new (DBusGAsyncData);
  stuff->cb = G_CALLBACK (callback);
  stuff->userdata = userdata;
  return dbus_g_proxy_begin_call (proxy, "Echo", com_openedhand_DBus_Tests_Echo_echo_async_callback, stuff, _dbus_glib_async_data_free, G_TYPE_STRING, IN_string, G_TYPE_INVALID);
}
#endif /* defined DBUS_GLIB_CLIENT_WRAPPERS_com_openedhand_DBus_Tests_Echo */

G_END_DECLS
